### ISSUE TITLE
Module loading problems in phantomjs

### ISSUE THREAD

**Issue by polarctos** [mike-north/ember-lodash#103]
I just upgraded to `ember-cli v2.13.1` and use `phantomjs v2.1.14`, and now the qunit tests are failing during module loading. The Tests run fine in Chrome though.

I am using `ember-lodash v4.17.2`.

```
<error message="
Died on test #1 moduleLoadFailure@http://localhost:10001/assets/test-support.js:15093:28
http://localhost:10001/assets/test-support.js:15321:33
require@http://localhost:10001/assets/test-support.js:15309:32
loadModules@http://localhost:10001/assets/test-support.js:15301:23
loadTests@http://localhost:10001/assets/test-support.js:15146:33
start@http://localhost:10001/assets/test-support.js:15181:16
http://localhost:10001/assets/tests.js:1194:28
exports@http://localhost:10001/assets/vendor.js:119:37
requireModule@http://localhost:10001/assets/vendor.js:34:25
global code@http://localhost:10001/assets/tests.js:1262:8: Object is not a constructor (evaluating '(0, _lodash_defineProperty['default'])')
">
```

**Comment by rwjblue** [comment]
I've seen this reported in slack a few times, and I'd love to help figure this out but I will need a reproduction..

**Comment by simonihmig** [comment]
OMG, I just lost so many hours debugging through this... 😢

Here are my findings...

In my case the use of lodash originated in `ember-cli-mirage`: https://github.com/samselikoff/ember-cli-mirage/blob/master/app/initializers/ember-cli-mirage.js#L6

Unfortunately this is in a private app I cannot share. I tried to reproduce it in a minimal app, but did not succeed. A fresh (ember-cli 2.13.1) app just with mirage and a dummy acceptance test did load the mirage initializer, but did not fail in Phantom unfortunately... 🤔

Here is the final part of the stack trace (I added the functions of lodash where the code lines come from):

```
http://localhost:7357/assets/vendor.js:231897:50  // lodash/_baseSetToString
http://localhost:7357/assets/vendor.js:236300:24 // lodash/_shortOut
baseRest@http://localhost:7357/assets/vendor.js:231790:47 // lodash/_baseRest
createAssigner@http://localhost:7357/assets/vendor.js:233130:44 // lodash/_createAssigner
http://localhost:7357/assets/vendor.js:237374:54 // lodash/assign
exports@http://localhost:7357/assets/vendor.js:119:37
```

`_baseSetToString` imports `_defineProperty` which is `null` in case of the failing app, thus the exception. 

I added a bunch of `console.log` here and there to track this down, always rerunning the tests in Phantom. (hey, debugging Phantom is so much fun 😩):

* `_defineProperty` calls `getNative(Object, 'defineProperty')` (https://github.com/lodash/lodash/blob/es/_defineProperty.js#L5)
* which calls `baseIsNative` (https://github.com/lodash/lodash/blob/es/_getNative.js#L14)
* which checks a couple of things to see if the function is really native (for whatever reason that is necessary) (https://github.com/lodash/lodash/blob/es/_getNative.js#L14)
* of these checks `isMasked` (https://github.com/lodash/lodash/blob/es/_isMasked.js) returns true, while it should actually return false. This causes `baseIsNative` to return false, so `getNative(Object, 'defineProperty')` returns `undefined`. In the minimal app, `isMasked` returns false, so the whole thing does work there. 
* in the magic that is done in `isMasked` (and which I totally don't understand), `maskSrcKey` is `Symbol(src)_1.p9e4qiyseg`, and `func[maskSrcKey]` is the native `defineProperty` function, so this returns `true` in this case. In the not-failing minimal app, `maskSrcKey` is empty

Anyone any idea what all that means? @rwjblue if not you, then who??? 😉

I could post my compiled `vendor.js` if that would help...

**Comment by bsaff** [comment]
@polarctos I have the same issue.  Do you have `includePolyfill` set to true in your ember-cli-build.js file? I was able to resolve my issue temporarily be disabling includePolyfill.

**Comment by rwjblue** [comment]
Will be fixed by https://github.com/mike-north/ember-lodash/pull/104.
