### ISSUE TITLE
Update ember-cli-babel dependency

### ISSUE THREAD

**Issue by adamreisnz** [mike-north/ember-lodash#117]
Can you please update the ember-cli-babel dependency so this module can be used with Node 8?
Currently it prevents installation due to:

```
error ember-cli-babel@6.1.0: The engine "node" is incompatible with this module. Expected version "^4.5 || 6.* || 7.*".
```

This requires a `--ignore-engines` flag to install at present which is cumbersome.

**Comment by riklaunim** [comment]
That would be nice.

**Comment by tchak** [comment]
done
