### ISSUE TITLE
Upgrade lodash-es to 4.x

### ISSUE THREAD

**Issue by fpauser** [mike-north/ember-lodash#19]
Why not move to lodash 4.x?

**Comment by amageed** [comment]
There is a PR for this, #17, but no response so far.

**Comment by Blackening999** [comment]
this is very annoying

**Comment by maxkwallace** [comment]
Hate to just chime in, but it'd be great to see some progress here! Does anyone know why the tests seem to be hanging in https://github.com/levanto-financial/ember-lodash/pull/17 ? Anything we can do to help out? I noticed there are three other PRs open as well.

**Comment by tchak** [comment]
I am working on the bump. Right now the problem I have is that latest version of `lodash-es` requires a `WeekMap` polyfill... At least I was not able to make it work without it for now.

**Comment by tchak** [comment]
new PR #22

**Comment by maxkwallace** [comment]
@tchak Awesome, thanks for the PR!

**Comment by Blackening999** [comment]
super annoying...

**Comment by lindem** [comment]
For those who can't wait, like me: You can always still user ember-browserify and import lodash directly, or just app.import() it in your ember-cli-build.js and have it ubiquitously available.

**Comment by oliverlangan** [comment]
We do in fact use app.import() to provide our own copy of lodash 4.x. However, when people mix-and-match our addon with others which in turn leverage ember-lodash, they end up with multiple copies/version of lodash in the vendor file. If 3.x loads after 4.x, it will preferentially use that.

**Comment by tchak** [comment]
🎉 🎉 🎉
