### ISSUE TITLE
Upgrade plan

### ISSUE THREAD

**Issue by tchak** [mike-north/ember-lodash#23]
I think we should align addon major version to lodash major version. So my current plan is to release a 3.0.0 and a 4.0.0 to allow for a clean upgrade.

@mike-north do you have any objections on this?

**Comment by mike-north** [comment]
agree

**Comment by cstolli** [comment]
:+1:  We would love to get some lodash 4.x on our ember

**Comment by liadb** [comment]
+1

**Comment by maxkoryukov** [comment]
Guys)) It is funny, but November is here..

* ember-lodash still on [`"lodash-es": "^3.10.0"`](https://github.com/mike-north/ember-lodash/blob/master/package.json#L54)
* lodash-es is [4.16.6 is the latest of 49 releases](https://www.npmjs.com/package/lodash-es)

May be it is time to merge **lodash-es-4.6.1** branch to master and/or publish on NPM?

**Comment by tchak** [comment]
@maxkoryukov the branch is not functional :( And as far as I know we still have no obvious solution for now.

**Comment by maxkoryukov** [comment]
@tchak , thank you for response... it is sad..

**Comment by flaviooliveri** [comment]
@tchak What is the problem of the branch? Can I help with something?

**Comment by maxkoryukov** [comment]
@flaviooliveri , it seems like all problems are described in #22
_PS: and they are beyond the scope of my competence.._

**Comment by tchak** [comment]
`lodash 3.10` was released

**Comment by tchak** [comment]
`lodash 4.17` was released

**Comment by patrickjholloway** [comment]
Are these releases going to get tagged soon?

**Comment by tchak** [comment]
@patrickjholloway they are released on npm

**Comment by patrickjholloway** [comment]
Awesome, thanks for getting this out! Totally appreciate it. :D
