### ISSUE TITLE
lodash-es not found on npm v3 due to nested dependency access

### ISSUE THREAD

**Issue by elwayman02** [mike-north/ember-lodash#5]
```
Error: ENOENT, no such file or directory '/app/node_modules/ember-lodash/node_modules/lodash-es'
```

This occurs because npm3 has a flat structure; there are no more nested `node_modules` directories. Now `lodash-es` lives on the top-level `node_modules` along with the main dependencies. As a result, we need a new way to load in the dependency for npm v3 users.

**Comment by BigGillyStyle** [comment]
As a workaround, I was able to `npm install` at the app level and get this error, `cd node_modules/ember-lodash`, then `npm install` at that level, jump back up to the app level and re-run `npm install` without the error any more.

@mike-north I'm not a JavaScript or NPM expert (in fact, I just took your Frontend Masters Ember 2 course online last week), but could I help out in some way with this issue?

**Comment by BigGillyStyle** [comment]
...and for those that are regretting upgrading to npm v3, you can install an older version by `sudo npm install -g npm@2.14.8`.  This Github issue wasn't the only problem I was finding in my Ember app as a result of "innocently" upgrading to npm v3.

**Comment by sharpshark28** [comment]
@BigGillyStyle thanks you just saved me a lot of fumbling about.

**Comment by halhenke** [comment]
Yeah this workaround worked for me (and was preferable to downgrading npm). Thanks @BigGillyStyle

**Comment by jherdman** [comment]
Closed via #4

**Comment by kellyselden** [comment]
My workaround from @BigGillyStyle for deploying to heroku:
```js
//package.json
{
  "scripts": {
    //...
    "postinstall": "cd node_modules/ember-lodash && npm install"
  }
}
```

**Comment by mattgrannary** [comment]
For some reason, PR #7 doesn't fix this situation for me. If I console log the path for the lodash-es dependency in the index.js, I get the appropriate path in my node_modules, but I'm still seeing the error that the dependency is not found.

My situation is the result of broccoli-sane-watcher failing to find the paths when booting an Ember-CLI 1.13.13 app.

**Comment by d10** [comment]
Yeah, this doesn't seem to have solved the issue.

**Comment by jakehow** [comment]
Running into this issue on a fresh ember 2.2 app also.

**Comment by iwaffles** [comment]
Seeing this one as well.

**Comment by iwaffles** [comment]
I tried the above solution from @BigGillyStyle, however it didn't work for me (locally). the only think that worked for me was to downgrade my npm version to 2.x

**Comment by tchak** [comment]
Close for lack of activity
