### ISSUE TITLE
failure upgrading to v4

### ISSUE THREAD

**Issue by kellyselden** [mike-north/ember-lodash#86]
I upgrading the references according the lodash v4 breaking changes:

`import pairs from 'lodash/object/pairs';` to `import toPairs from 'lodash/toPairs';`

I also tried `import { toPairs } from 'lodash';`.

```
ReferenceError: lodash/_castPath.js: unknown node of type undefined with constructor "Function"
```

https://travis-ci.org/kellyselden/package-hint-historic-resolver/jobs/186700644#L654
https://github.com/kellyselden/package-hint-historic-resolver/pull/296/files

**Comment by tchak** [comment]
I was not able to reproduce in a new app, addon or tests for now. I will continue to investigate. It looks like another babel transpilation issue :(

**Comment by cs3b** [comment]
@tchak can we close this ticket? (I use v4, and it works well)

**Comment by kellyselden** [comment]
I don't see why you would. I have a reproducible branch linked above.

**Comment by tchak** [comment]
@kellyselden I checked out your app and started removing addons to find which one is conflicting. Have not got the chance to finish (there is a lot of addons in there :)) I am pretty sure it is a conflict with on of the addons.

**Comment by kellyselden** [comment]
> there is a lot of addons in there :)

It's been very good at catching regressions in addons because of how complicated it is lol.

**Comment by kellyselden** [comment]
Out of curiosity, I tried this upgrade in a closed source app as well. I get the same error:

```
ReferenceError: lodash/_castPath.js: unknown node of type undefined with constructor "Function"
```

**Comment by JackCA** [comment]
I'm also running into this. @kellyselden have you found a solution in the meantime?

**Comment by kellyselden** [comment]
@JackCA Nope, still on 3.x on my projects.

**Comment by gabrielgrant** [comment]
I seem to be running into the same error after installing `ember-awesome-macros` -- @tchak not sure if that's the source of the error that you're looking for in @kellyselden 's (not-so-minimal) MCVE?

**Comment by kellyselden** [comment]
Thank you @gabrielgrant. You were right. New app + ember-lodash works. then + ember-awesome-macros breaks. And I think I know why. I'm using a babel plugin in that project. I will now start tracking that issue down. Thanks for the guidance, and sorry for the noise.

**Comment by gabrielgrant** [comment]
Glad that helped track down the issue. For others: uninstalling and reinstalling `ember-awesome-macros` pulls in @kellyselden 's [new code in `babel-plugin-fake-import-specifiers`](kellyselden/babel-plugin-fake-import-specifiers#12) and fixes  the issue.

Thanks for the quick follow-up @kellyselden !

**Comment by kellyselden** [comment]
@gabrielgrant You beat me to the comment! Thanks.

@JackCA should be fixed now.

**Comment by tchak** [comment]
\o/
