### ISSUE TITLE
Could not find module `lodash/merge` in ember-cli 2.12

### ISSUE THREAD

**Issue by cibernox** [mike-north/ember-lodash#89]
I just updated the ember-cli version in one addon and I can't make this addon work.

**Repo**: https://github.com/cibernox/ember-assign-helper/tree/allow-deep-merge
**Steps**: 
- Install and run the tests. Should be green.
- Update ember-cli to 2.12.0-beta.1
- Run the tests. Tests fail now.

Any idea?

**Comment by samselikoff** [comment]
Same, running into problems on Mirage upgrading to 2.12.0-beta.1

**Comment by shaunc** [comment]
I just installed in an addon using 2.12.0-beta.1. Having problem: 

```
Could not find module `lodash` imported from `ember-column-index/column-index/component`
```
Which includes:

    import { sortBy } from 'lodash';

My first instinct was that this was a problem because I'm developing an addon, but probably this issue, actually (addons should work, right)?

**Comment by mfazekas** [comment]
I think the issue is likely with the following added condition in ember-cli as of https://github.com/ember-cli/ember-cli/pull/6530

```
    if (this._fileSystemInfo().hasJSFiles) {
      var processedJsFiles = this.preprocessJs(this.addonJsFiles(tree), '/', this.name, {
       ...
     }
```

since ember-lodash itself has no js files preprocessJs will not be called

**Comment by rwjblue** [comment]
Yep, but generally speaking, that guard is good (it prevents wasted build work for many addons that _only_ have `addon/.gitkeep` and no `*.js` files).  I refactored slightly in https://github.com/ember-cli/ember-cli/pull/6808 (which targets 2.12.0-beta.2) to make it easier for addons to control their own destiny though.

**Comment by samselikoff** [comment]
@rwjblue is it possible to check the addon's tree instead of the files on disk? I'm wondering if this Ember CLI change will break lots of addons

**Comment by rwjblue** [comment]
> is it possible to check the addon's tree instead of the files on disk?

Not really

> I'm wondering if this Ember CLI change will break lots of addons

I doubt it.  There are not many addons that do this kind of thing AFAICT.

**Comment by tchak** [comment]
@rwjblue if I add an empty js file to the project it should fix it?

**Comment by rwjblue** [comment]
Yes, but https://github.com/ember-cli/ember-cli/pull/6808 allows implementing `_shouldCompileJS: function() {  return true; },` in your main entry point (`index.js`) instead of that...

**Comment by josemarluedke** [comment]
This bug was not fixed by the latest release (v4.17.1). I have a reproduction here: https://github.com/josemarluedke/try-em-ld 

I'm using ember-cli v2.12.0-beta.1

**Comment by rwjblue** [comment]
Yep. Requires beta.2 (and for me to release it).

**Comment by mfazekas** [comment]
@josemarluedke for beta1 you can do something like this: https://github.com/mfazekas/ember-lodash/commit/549189311dbdca4fdc7a5fdaf711a470cdb70049

or you can just add `"ember-lodash": "github:mfazekas/ember-lodash#ember-212-beta1-fix",` to your package.json.

But beta.2 should be out very soon

**Comment by tchak** [comment]
I would rather not introduce temporary fixes for a soon to be released beta...
