### ISSUE TITLE
this._super is not a function

### ISSUE THREAD

**Issue by ngouy** [mike-north/ember-lodash#90]
i'm trying to install it on an addon.

I ran `ember install ember-lodash`

when I run `ember s` it throws

![screen shot 2017-01-30 at 16 26 20](https://cloud.githubusercontent.com/assets/12391171/22428857/e4591296-e708-11e6-8ff9-355dcc8912e3.png)

**Comment by zkwentz** [comment]
What version of ember are you on?

**Comment by sescobb27** [comment]
i'm getting this issue too, i'm upgrading from
`ember 2.9.0` to `2.11.0`
`ember-data 2.9.0` to `2.11.0`
`ember-lodash 0.0.6` to `4.17.0`

**Comment by kevinyuliawan** [comment]
Also ran into this on `ember 1.13.13`, my solution was to just use `ember-lodash 3.10.0` for now.
